category_dict = {
    1: 'carrot',
    2: 'cucumber',
    3: 'green bell pepper',
    4: 'green chili pepper',
    5: 'red bell pepper',
    6: 'red chili pepper',
    7: 'eggplant',
    8: 'corn',
    9: 'drawer',
    10: 'chest of drawers',
    11: 'handle',
    12: 'box, basket, case, bin, container',
    13: 'toy cat',
    14: 'white toy',
    15: 'toy block',
    16: 'garlic',
    17: 'tomato',
    18: 'potato',
    19: 'floor',
    20: 'wall',
    21: 'person',
    22: 'key',
    23: 'gripper',
    24: 'door',
    25: 'poster',
    26: 'table',
    27: 'ceiling'
}